######################## default configuration ####################
baseURL = "https://neztra.com/"
languageCode = "id-in"
title = "Neztra | Website Resep Sehat"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = "neztra"
buildDrafts = false
timeout = 100000
enableRobotsTXT = true
canonifyURLs = true
[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "https://cdnjs.cloudflare.com/ajax/libs/venobox/1.9.3/venobox.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
  [[params.plugins.js]]
  URL = "https://cdnjs.cloudflare.com/ajax/libs/venobox/1.9.3/venobox.min.js"
  [[params.plugins.js]]
  URL = "https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.4.6/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Beranda"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Resep"
  URL = "resep"
  weight = 2

  [[menu.main]]
  name = "Artikel"
  URL = "artikel"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Beranda"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Resep"
  URL = "resep"
  weight = 2

  [[menu.main]]
  name = "Artikel"
  URL = "artikel"
  weight = 3

#################### default parameters ################################
[params]
logo = "images/logo.png"
feature = "images/banner.png"
home = "Beranda"
# Meta data
description = "Situs web pecinta kuliner tempat Anda dapat menemukan resep sehat tentang vegan, keto, dan masih banyak lainya."
author = "Neztra"
# Google Analitycs
googleAnalitycsID = "G-P0WW95WJ14"
googleAnalytics = "G-P0WW95WJ14"
# Contact Information
mobile = ""
email = "info@neztra.com"
location = "Surabaya, Indonesia"
# copyright
copyright = "| copyright &copy; 2020 [The Nomad Coder](https://thenomadcoder.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join My Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social site ########################
[[params.social]]
title = "Pinterest"
icon = "ti-pinterest" # themify icon : https://themify.me/themify-icons
link = "http://pinterest.com/neztraa/"

[[params.social]]
title = "Twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "http://twitter.com/neztraa/"

[[params.social]]
title = "Instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/neztraa1/"

[[params.social]]
title = "Facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "http://facebook.com/neztraa/"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "javascript:void(0)"

############################# deploy ########################
[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[minify]
  minifyOutput = true

############################# Image Processing ########################
[imaging]

# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG or WEBP quality setting. Default is 75.
quality = 100

# Default hint about what type of image. Currently only used for Webp encoding.
# Default is "photo".
# Valid values are "picture", "photo", "drawing", "icon", or "text".
hint = "photo"

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

# Default background color.
# Hugo will preserve transparency for target formats that supports it,
# but will fall back to this color for JPEG.
# Expects a standard HEX color string with 3 or 6 digits.
# See https://www.google.com/search?q=color+picker
bgColor = "#ffffff"