######################## default configuration ####################
baseURL = "//neztra.com"
languageCode = "id-in"
title = "Neztra | Website Resep Sehat"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
buildDrafts = false
#ignorecache = false
timeout = 30000 
[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Beranda"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Resep"
  URL = "resep"
  weight = 2

  [[menu.main]]
  name = "Artikel"
  URL = "artikel"
  weight = 3

  # main menu
  [[menu.main]]
  name = "Tentang"
  URL = "tentang"
  weight = 4

  #[[menu.main]]
  #name = "Contact"
  #URL = "contact"
  #weight = 5

  # footer menu
  [[menu.footer]]
  name = "Beranda"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Resep"
  URL = "resep"
  weight = 2

  [[menu.main]]
  name = "Artikel"
  URL = "artikel"
  weight = 3

  [[menu.footer]]
  name = "Tentang"
  URL = "tentang"
  weight = 4

  #[[menu.footer]]
  #name = "Contact"
  #URL = "contact"
  #weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Beranda"
# Meta data
description = "Situs web pecinta kuliner tempat Anda dapat menemukan resep sehat tentang vegan, keto, dan masih banyak lainya."
author = "Neztra"
# Google Analitycs
googleAnalitycsID = "G-P0WW95WJ14"
# Contact Information
mobile = ""
email = "info@neztra.com"
location = "Surabaya, Indonesia"
# copyright
copyright = "| copyright &copy; 2020 [The Nomad Coder](https://thenomadcoder.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join My Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "pinterest"
icon = "ti-pinterest" # themify icon : https://themify.me/themify-icons
link = "https://nl.pinterest.com/ineztraphun/"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/nestra_phun/"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/nestra.phun"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "javascript:void(0)"

############################# deploy ########################
[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
